version: "3.7"
services:
  # TODO база данных вроде работает, но сообщения не работают и авторизация тоже - надо выяснить почему
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fast_api/docker/app.sh"]
    ports:
      - 8080:8000
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: celery_app
    command: ["/fast_api/docker/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: flower_app
    command: ["/fast_api/docker/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555